### ISSUE TITLE
mmh installation is run every time at startup

### ISSUE THREAD

**Issue by hishizuka** [thingsboard/thingsboard-python-client-sdk#48] opened 2023-09-28 21:32 UTC
Hi,
I am using your ThingsBoard library on a Raspberry Pi Zero. 
It is a valuable piece of software that allows me to track my current location on a map and display my planned driving route on the dashboard.
https://github.com/hishizuka/pizero_bikecomputer

Now, I report the problem.
This program runs the mmh install every time it starts up, according to the code after line 23 of sdk_utils.py.
With the Raspberry Pi Zero's processing power, it takes almost a minute to run the pip command, which is a pain.
Is it possible to use requirements.txt during installation and make it a one-time install check?

**Comment by vinicentus** [comment] 2023-11-17 11:57
duplicate of #39

**Closed** 2023-11-17 13:19 UTC
